/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AguaDao;
import dao.ApartamentoDao;
import dao.BlocoDao;
import dao.CondominioDao;
import dao.EsgotoDao;
import dao.GasDao;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Agua;
import model.Condominio;
import model.Esgoto;
import model.Gas;

/**
 *
 * @author lucasreinert
 */
public class CadastroConsumos extends javax.swing.JDialog {

    /**
     * Creates new form CadastroDeConsumos
     */
    public CadastroConsumos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    int i = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edCon01 = new javax.swing.JTextField();
        edCon02 = new javax.swing.JTextField();
        edCon03 = new javax.swing.JTextField();
        edCon06 = new javax.swing.JTextField();
        edCon05 = new javax.swing.JTextField();
        edCon04 = new javax.swing.JTextField();
        edCon12 = new javax.swing.JTextField();
        edCon11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edCon10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edCon07 = new javax.swing.JTextField();
        edCon08 = new javax.swing.JTextField();
        edCon09 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        edCodCon = new javax.swing.JTextField();
        edCodBlo = new javax.swing.JTextField();
        edCodApa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbTipoConsumo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        edAno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Janeiro");

        jLabel2.setText("Fevereiro");

        jLabel3.setText("Março");

        jLabel4.setText("Abril");

        jLabel5.setText("Março");

        jLabel6.setText("Junho");

        edCon04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCon04ActionPerformed(evt);
            }
        });

        edCon11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCon11ActionPerformed(evt);
            }
        });

        jLabel13.setText("Julho");

        jLabel14.setText("Agosto");

        jLabel15.setText("Setembro");

        jLabel16.setText("Outubro");

        jLabel17.setText("Novembro");

        jLabel18.setText("Dezembro");

        jLabel7.setText("Consumo");

        jLabel10.setText("Consumo");

        jLabel11.setText("Condomínio");

        jLabel12.setText("Bloco");

        jLabel19.setText("Apartamento");

        jLabel20.setText("Tipo de consumo");

        cbTipoConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Água", "Esgoto", "Gás" }));
        cbTipoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoConsumoActionPerformed(evt);
            }
        });

        jLabel21.setText("Ano");

        edAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edAnoFocusLost(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edCon04, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(edCon05)
                                    .addComponent(edCon06)
                                    .addComponent(edCon03, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edCon02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addComponent(edCon01, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edCon12)
                                        .addComponent(edCon11)
                                        .addComponent(edCon10)
                                        .addComponent(edCon07)
                                        .addComponent(edCon08)
                                        .addComponent(edCon09, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edCodApa, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(edCodBlo)
                            .addComponent(edCodCon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edAno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edCodCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cbTipoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edCodBlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(edAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(edCodApa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(edCon01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edCon02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edCon03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edCon04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edCon05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel17))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edCon06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel18)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(edCon07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(edCon08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(edCon09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edCon12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(edCon10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(19, 19, 19)
                                .addComponent(edCon11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edCon04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCon04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCon04ActionPerformed

    private void edCon11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCon11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCon11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        CondominioDao condDao = new CondominioDao();
        if (condDao.FindKey(Integer.parseInt(edCodCon.getText()))) {
            BlocoDao blocoDao = new BlocoDao();
            if (blocoDao.FindKey(Integer.parseInt(edCodCon.getText()), Integer.parseInt(edCodBlo.getText()))) {
                ApartamentoDao apDao = new ApartamentoDao();
                if (apDao.FindKey(Integer.parseInt(edCodCon.getText()), Integer.parseInt(edCodBlo.getText()), Integer.parseInt(edCodApa.getText()))) {
                    switch (cbTipoConsumo.getSelectedIndex()) {
                        case 0:
                            Agua agu = new Agua();
                            agu.setAno(Integer.parseInt(edAno.getText()));
                            agu.setIdCond(Integer.parseInt(edCodCon.getText()));
                            agu.setIdApart(Integer.parseInt(edCodApa.getText()));
                            agu.setIdBloco(Integer.parseInt(edCodBlo.getText()));
                            if (!edCon01.getText().isEmpty()) {
                                agu.setLei01(Float.parseFloat(edCon01.getText()));
                            }
                            if (!edCon02.getText().isEmpty()) {
                                agu.setLei02(Float.parseFloat(edCon02.getText()));
                            }
                            if (!edCon03.getText().isEmpty()) {
                                agu.setLei03(Float.parseFloat(edCon03.getText()));
                            }
                            if (!edCon04.getText().isEmpty()) {
                                agu.setLei04(Float.parseFloat(edCon04.getText()));
                            }
                            if (!edCon05.getText().isEmpty()) {
                                agu.setLei05(Float.parseFloat(edCon05.getText()));
                            }
                            if (!edCon06.getText().isEmpty()) {
                                agu.setLei06(Float.parseFloat(edCon06.getText()));

                            }
                            if (!edCon07.getText().isEmpty()) {
                                agu.setLei07(Float.parseFloat(edCon07.getText()));

                            }
                            if (!edCon08.getText().isEmpty()) {
                                agu.setLei08(Float.parseFloat(edCon08.getText()));

                            }
                            if (!edCon09.getText().isEmpty()) {
                                agu.setLei09(Float.parseFloat(edCon09.getText()));

                            }
                            if (!edCon10.getText().isEmpty()) {
                                agu.setLei10(Float.parseFloat(edCon10.getText()));

                            }
                            if (!edCon11.getText().isEmpty()) {
                                agu.setLei11(Float.parseFloat(edCon11.getText()));

                            }
                            if (!edCon12.getText().isEmpty()) {
                                agu.setLei12(Float.parseFloat(edCon12.getText()));

                            }
                            AguaDao aguDao = new AguaDao();
                            if (aguDao.listar(agu) == null) {
                                aguDao.adicionar(agu);
                            } else {
                                aguDao.atualizar(agu);
                            }
                            break;
                        case 1:
                            Esgoto esg = new Esgoto();
                            esg.setAno(Integer.parseInt(edAno.getText()));
                            esg.setIdCond(Integer.parseInt(edCodCon.getText()));
                            esg.setIdApart(Integer.parseInt(edCodApa.getText()));
                            esg.setIdBloco(Integer.parseInt(edCodBlo.getText()));
                            if (!edCon01.getText().isEmpty()) {
                                esg.setLei01(Float.parseFloat(edCon01.getText()));

                            }
                            if (!edCon02.getText().isEmpty()) {
                                esg.setLei02(Float.parseFloat(edCon02.getText()));

                            }
                            if (!edCon03.getText().isEmpty()) {
                                esg.setLei03(Float.parseFloat(edCon03.getText()));

                            }
                            if (!edCon04.getText().isEmpty()) {
                                esg.setLei04(Float.parseFloat(edCon04.getText()));

                            }
                            if (!edCon05.getText().isEmpty()) {
                                esg.setLei05(Float.parseFloat(edCon05.getText()));

                            }
                            if (!edCon06.getText().isEmpty()) {
                                esg.setLei06(Float.parseFloat(edCon06.getText()));

                            }
                            if (!edCon07.getText().isEmpty()) {
                                esg.setLei07(Float.parseFloat(edCon07.getText()));

                            }
                            if (!edCon08.getText().isEmpty()) {
                                esg.setLei08(Float.parseFloat(edCon08.getText()));

                            }
                            if (!edCon09.getText().isEmpty()) {
                                esg.setLei09(Float.parseFloat(edCon09.getText()));

                            }
                            if (!edCon10.getText().isEmpty()) {
                                esg.setLei10(Float.parseFloat(edCon10.getText()));

                            }
                            if (!edCon11.getText().isEmpty()) {
                                esg.setLei11(Float.parseFloat(edCon11.getText()));

                            }
                            if (!edCon12.getText().isEmpty()) {
                                esg.setLei12(Float.parseFloat(edCon12.getText()));

                            }
                            EsgotoDao esgDao = new EsgotoDao();
                            if (esgDao.listar(esg) == null) {
                                esgDao.adicionar(esg);
                            } else {
                                esgDao.atualizar(esg);
                            }
                            break;
                        case 2:
                            Gas gas = new Gas();
                            gas.setAno(Integer.parseInt(edAno.getText()));
                            gas.setIdCond(Integer.parseInt(edCodCon.getText()));
                            gas.setIdApart(Integer.parseInt(edCodApa.getText()));
                            gas.setIdBloco(Integer.parseInt(edCodBlo.getText()));
                            if (!edCon01.getText().isEmpty()) {
                                gas.setLei01(Float.parseFloat(edCon01.getText()));

                            }
                            if (!edCon02.getText().isEmpty()) {
                                gas.setLei02(Float.parseFloat(edCon02.getText()));

                            }
                            if (!edCon03.getText().isEmpty()) {
                                gas.setLei03(Float.parseFloat(edCon03.getText()));

                            }
                            if (!edCon04.getText().isEmpty()) {
                                gas.setLei04(Float.parseFloat(edCon04.getText()));

                            }
                            if (!edCon05.getText().isEmpty()) {
                                gas.setLei05(Float.parseFloat(edCon05.getText()));

                            }
                            if (!edCon06.getText().isEmpty()) {
                                gas.setLei06(Float.parseFloat(edCon06.getText()));

                            }
                            if (!edCon07.getText().isEmpty()) {
                                gas.setLei07(Float.parseFloat(edCon07.getText()));

                            }
                            if (!edCon08.getText().isEmpty()) {
                                gas.setLei08(Float.parseFloat(edCon08.getText()));

                            }
                            if (!edCon09.getText().isEmpty()) {
                                gas.setLei09(Float.parseFloat(edCon09.getText()));

                            }
                            if (!edCon10.getText().isEmpty()) {
                                gas.setLei10(Float.parseFloat(edCon10.getText()));
                            }
                            if (!edCon11.getText().isEmpty()) {
                                gas.setLei11(Float.parseFloat(edCon11.getText()));
                            }
                            if (!edCon12.getText().isEmpty()) {
                                gas.setLei12(Float.parseFloat(edCon12.getText()));
                            }
                            GasDao gasDao = new GasDao();
                            if (gasDao.listar(gas) == null) {
                                gasDao.adicionar(gas);
                            } else {
                                gasDao.atualizar(gas);
                            }
                            break;
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Apartamento não encontrado");
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Bloco não encontrado");
            }
        } else {
            JOptionPane.showConfirmDialog(null, "Condomínio não encontrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbTipoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoConsumoActionPerformed

    private void edAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edAnoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_edAnoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConsumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroConsumos dialog = new CadastroConsumos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoConsumo;
    private javax.swing.JTextField edAno;
    private javax.swing.JTextField edCodApa;
    private javax.swing.JTextField edCodBlo;
    private javax.swing.JTextField edCodCon;
    private javax.swing.JTextField edCon01;
    private javax.swing.JTextField edCon02;
    private javax.swing.JTextField edCon03;
    private javax.swing.JTextField edCon04;
    private javax.swing.JTextField edCon05;
    private javax.swing.JTextField edCon06;
    private javax.swing.JTextField edCon07;
    private javax.swing.JTextField edCon08;
    private javax.swing.JTextField edCon09;
    private javax.swing.JTextField edCon10;
    private javax.swing.JTextField edCon11;
    private javax.swing.JTextField edCon12;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
